In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity="all"

In [2]:
#import PyPDF2

In [3]:
def cria_lista_1(df):
    df=df[df["profissão"]!="SEM REPRESENTAÇÃO NA LISTA"]
    estados=["ACRE","ALAGOAS","AMAPÁ","AMAZONAS","BAHIA",
         "CEARÁ","DISTRITO FEDERAL","ESPÍRITO SANTO","GOIÁS",
        "MARANHÃO","MATO GROSSO","MATO GROSSO DO SUL","MINAS GERAIS","PARÁ","PARAÍBA","PARANÁ",
           "PERNAMBUCO","PIAUÍ","RIO DE JANEIRO","RIO GRANDE DO NORTE","RIO GRANDE DO SUL",
           "RONDÔNIA","RORAIMA","SANTA CATARINA","SÃO PAULO","SERGIPE","TOCANTINS"]
    lista=[]
    linhas=len(df)
    i=0
    while i < linhas:
        profissão=df.iloc[i]["profissão"]
        if profissão in estados:
            estado=profissão
            print(estado)
        else:
            reg={}
            nome_part=df.iloc[i]["Nome-partido"]
            reg["nome"]=nome_part.split("-")[0].strip().title()
            reg["partido"]=nome_part.split("-")[1]
            reg["cargo"]=(df.iloc[i]["cargo"]).title()
            reg["estado"]=estado
            reg["profissão"]=(df.iloc[i]["profissão"]).title()
            reg["mandatos"]=df.iloc[i]["mandatos"][0]
            reg["cabeças"]=df.iloc[i]["cabeças"]
            reg["debatedor"]=df.iloc[i]["debatedor"]
            reg["articulador"]=df.iloc[i]["articulador"]
            reg["formulador"]=df.iloc[i]["formulador"]
            reg["negociador"]=df.iloc[i]["negociador"]
            print("Nome: {}, Estado: {}, Partido: {} cargo: {}".format(reg["nome"],
                                                                       reg["estado"],
                                                                       reg["partido"],
                                                                       reg["cargo"]))
            lista.append(reg)
        i+=1
    return lista

In [4]:
!ls ../dados/diap

oscabecasdocongressonacional_2019.pdf  politicos_diap.csv
pag_17.csv			       politicos_diap_old.csv
pag_18.csv

In [5]:
pag_17=pd.read_csv("../dados/diap/pag_17.csv")
pag_17.shape
pag_17.info()

(66, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cargo         47 non-null     object
 1   Nome-partido  47 non-null     object
 2   profissão     66 non-null     object
 3   mandatos      47 non-null     object
 4   cabeças       47 non-null     float64
 5   debatedor     11 non-null     object
 6   articulador   16 non-null     object
 7   formulador    9 non-null      object
 8   negociador    11 non-null     object
dtypes: float64(1), object(8)
memory usage: 4.8+ KB

In [6]:
pag_17.head()

,cargo,Nome-partido,profissão,mandatos,cabeças,debatedor,articulador,formulador,negociador
0,NaN,NaN,ACRE,NaN,NaN,NaN,NaN,NaN,NaN
1,SENADOR,SÉRGIO PETECÃO - PSD,EMPRESÁRIO,1o,1.0,NaN,X,NaN,NaN
2,NaN,NaN,ALAGOAS,NaN,NaN,NaN,NaN,NaN,NaN
3,Deputado,Arthur Lira - PP,Empresário,3°,3.0,NaN,X,NaN,NaN
4,Senador,Renan Calheiros - MDB,Produtor Rural,4°,23.0,NaN,X,NaN,NaN

In [7]:

pag_17["debatedor"][pag_17["debatedor"]!="X"]=0
pag_17["debatedor"][pag_17["debatedor"]=="X"]=1
pag_17["articulador"][pag_17["articulador"]!="X"]=0
pag_17["articulador"][pag_17["articulador"]=="X"]=1
pag_17["formulador"][pag_17["formulador"]!="X"]=0
pag_17["formulador"][pag_17["formulador"]=="X"]=1
pag_17["negociador"][pag_17["negociador"]!="X"]=0
pag_17["negociador"][pag_17["negociador"]=="X"]=1
pag_17.head()

/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cargo,Nome-partido,profissão,mandatos,cabeças,debatedor,articulador,formulador,negociador
0,NaN,NaN,ACRE,NaN,NaN,0,0,0,0
1,SENADOR,SÉRGIO PETECÃO - PSD,EMPRESÁRIO,1o,1.0,0,1,0,0
2,NaN,NaN,ALAGOAS,NaN,NaN,0,0,0,0
3,Deputado,Arthur Lira - PP,Empresário,3°,3.0,0,1,0,0
4,Senador,Renan Calheiros - MDB,Produtor Rural,4°,23.0,0,1,0,0

In [8]:
lista_pag_17=cria_lista_1(pag_17)

ACRE
Nome: Sérgio Petecão, Estado: ACRE, Partido:  PSD cargo: Senador
ALAGOAS
Nome: Arthur Lira, Estado: ALAGOAS, Partido:  PP cargo: Deputado
Nome: Renan Calheiros, Estado: ALAGOAS, Partido:  MDB cargo: Senador
AMAPÁ
Nome: Davi Alcolumbre, Estado: AMAPÁ, Partido:  DEM cargo: Senador
Nome: Randolfe Rodrigues, Estado: AMAPÁ, Partido:  REDE cargo: Senador
AMAZONAS
Nome: Eduardo Braga, Estado: AMAZONAS, Partido:  MDB cargo: Senador
Nome: Marcelo Ramos, Estado: AMAZONAS, Partido:  PL cargo: Deputado
Nome: Omar Aziz, Estado: AMAZONAS, Partido:  PSD cargo: Senador
BAHIA
Nome: Afonso Florence, Estado: BAHIA, Partido:  PT cargo: Deputado
Nome: Alice Portugal, Estado: BAHIA, Partido:  PCdoB cargo: Deputada
Nome: Daniel Almeida, Estado: BAHIA, Partido:  PCdoB cargo: Deputado
Nome: Elmar Nascimento, Estado: BAHIA, Partido:  DEM cargo: Deputado
Nome: Jaques Wagner, Estado: BAHIA, Partido:  PT1 cargo: Senador
Nome: João Roma, Estado: BAHIA, Partido:  PRB cargo: Deputado
Nome: Otto Alencar, Estado: BAHIA, Partido:  PSD cargo: Senador
CEARÁ
Nome: André Figueiredo, Estado: CEARÁ, Partido:  PDT cargo: Deputado
Nome: Cid Gomes, Estado: CEARÁ, Partido:  PDT cargo: Senador
Nome: José Guimarães, Estado: CEARÁ, Partido:  PT cargo: Deputado
Nome: Tasso Jereissati, Estado: CEARÁ, Partido:  PSDB cargo: Senador
DISTRITO FEDERAL
Nome: Erika Kokay, Estado: DISTRITO FEDERAL, Partido:  PT cargo: Deputada
ESPÍRITO SANTO
GOIÁS
Nome: Delegado Waldir, Estado: GOIÁS, Partido:  PSL cargo: Deputado
Nome: João Campos, Estado: GOIÁS, Partido:  PRB cargo: Deputado
Nome: Major Vitor Hugo, Estado: GOIÁS, Partido:  PSL cargo: Deputado
MARANHÃO
Nome: Roberto Rocha, Estado: MARANHÃO, Partido:  PSDB cargo: Senador
Nome: Weverton Rocha, Estado: MARANHÃO, Partido:  PDT cargo: Senador
MATO GROSSO
MATO GROSSO DO SUL
Nome: Fábio Trad, Estado: MATO GROSSO DO SUL, Partido:  PSD cargo: Deputado
Nome: Simone Tebet, Estado: MATO GROSSO DO SUL, Partido:  MDB cargo: Senadora
MINAS GERAIS
Nome: Aécio Neves, Estado: MINAS GERAIS, Partido:  PSDB cargo: Deputado
Nome: Antonio Anastasia, Estado: MINAS GERAIS, Partido:  PSDB cargo: Senador
Nome: Fred Costa, Estado: MINAS GERAIS, Partido:  PATRIOTA cargo: Deputado
Nome: Júlio Delgado, Estado: MINAS GERAIS, Partido:  PSB cargo: Deputado
Nome: Lincoln Portela, Estado: MINAS GERAIS, Partido:  PL cargo: Deputado
Nome: Paulo Abi, Estado: MINAS GERAIS, Partido: Ackel  cargo: Deputado
Nome: Rodrigo Pacheco, Estado: MINAS GERAIS, Partido:  DEM cargo: Senador
PARÁ
PARAÍBA
Nome: Aguinaldo Ribeiro, Estado: PARAÍBA, Partido:  PP cargo: Deputado
Nome: Daniella Ribeiro, Estado: PARAÍBA, Partido:  PP cargo: Senadora
Nome: Efraim Filho, Estado: PARAÍBA, Partido:  DEM cargo: Deputado
Nome: Veneziano Vital Do Rêgo, Estado: PARAÍBA, Partido:  PSB cargo: Senador
Nome: Wellington Roberto, Estado: PARAÍBA, Partido:  PL cargo: Deputado
PARANÁ
Nome: Enio Verri, Estado: PARANÁ, Partido:  PT cargo: Deputado
Nome: Felipe Francischini, Estado: PARANÁ, Partido:  PSL cargo: Deputado
Nome: Filipe Barros, Estado: PARANÁ, Partido:  PSL cargo: Deputado
Nome: Gleisi Hoffmann, Estado: PARANÁ, Partido:  PT1 cargo: Deputada
Nome: Gustavo Fruet, Estado: PARANÁ, Partido:  PDT cargo: Deputado
Nome: Ricardo Barros, Estado: PARANÁ, Partido:  PP cargo: Deputado
Nome: Rubens Bueno, Estado: PARANÁ, Partido:  CIDADANIA cargo: Deputado
Nome: Sérgio Souza, Estado: PARANÁ, Partido:  MDB cargo: Deputado

In [9]:
pag_18=pd.read_csv("../dados/diap/pag_18.csv")
pag_18.shape
pag_18.info()
pag_18.head()

(66, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cargo         53 non-null     object
 1   Nome-partido  66 non-null     object
 2   profissão     0 non-null      float64
 3   mandatos      53 non-null     object
 4   cabeças       53 non-null     float64
 5   debatedor     15 non-null     object
 6   articulador   21 non-null     object
 7   formulador    7 non-null      object
 8   negociador    10 non-null     object
dtypes: float64(2), object(7)
memory usage: 4.8+ KB

,cargo,Nome-partido,profissão,mandatos,cabeças,debatedor,articulador,formulador,negociador
0,NaN,PERNAMBUCO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DEPUTADO,ANDRÉ DE PAULA - PSD ADVOGADO,NaN,6o,1.0,NaN,X,NaN,NaN
2,DEPUTADO,ANDRÉ FERREIRA - PSC EMPRESÁRIO,NaN,1o,1.0,NaN,NaN,NaN,X
3,DEPUTADO,AUGUSTO COUTINHO - SOLIDARIEDADE ENGENHEIRO CIVIL,NaN,3o,1.0,NaN,NaN,NaN,X
4,DEPUTADO,DANIEL COELHO - CIDADANIA EMPRESÁRIO,NaN,2o,1.0,NaN,X,NaN,NaN

In [10]:
nome_partido_profissão=pag_18.iloc[3]["Nome-partido"]
nome_partido_profissão.split("-")
nome=nome_partido_profissão.split("-")[0].strip()
nome
partido_profissão=nome_partido_profissão.split("-")[1].strip()
partido_profissão
partido=partido_profissão.split(" ")[0]
partido
profissão=partido_profissão.partition(" ")[2]
profissão
#partido[1].partition(" ")

['AUGUSTO COUTINHO ', ' SOLIDARIEDADE ENGENHEIRO CIVIL']

'AUGUSTO COUTINHO'

'SOLIDARIEDADE ENGENHEIRO CIVIL'

'SOLIDARIEDADE'

'ENGENHEIRO CIVIL'

In [11]:
def cria_lista_2(df):
    df=df[df["Nome-partido"]!="SEM REPRESENTAÇÃO NA LISTA"]
    estados=["ACRE","ALAGOAS","AMAPÁ","AMAZONAS","BAHIA",
         "CEARÁ","DISTRITO FEDERAL","ESPÍRITO SANTO","GOIÁS",
        "MARANHÃO","MATO GROSSO","MATO GROSSO DO SUL","MINAS GERAIS","PARÁ","PARAÍBA","PARANÁ",
           "PERNAMBUCO","PIAUÍ","RIO DE JANEIRO","RIO GRANDE DO NORTE","RIO GRANDE DO SUL",
           "RONDÔNIA","RORAIMA","SANTA CATARINA","SÃO PAULO","SERGIPE","TOCANTINS"]
    lista=[]
    linhas=len(df)
    i=0
    while i < linhas:
        nome_partido_profissão=df.iloc[i]["Nome-partido"]
        if nome_partido_profissão in estados:
            estado=nome_partido_profissão
            print(estado)
        else:
            reg={}
            nome_partido_profissão=nome_partido_profissão.replace("–","-")
            reg["nome"]=nome_partido_profissão.split("-")[0].strip().title()
            partido_profissão=nome_partido_profissão.split("-")[1].strip()
            reg["partido"]=partido_profissão.split(" ")[0]
            reg["profissão"]=partido_profissão.partition(" ")[2].title()
            reg["estado"]=estado
            reg["mandatos"]=df.iloc[i]["mandatos"][0]
            reg["cargo"]=(df.iloc[i]["cargo"]).title()
            reg["cabeças"]=df.iloc[i]["cabeças"]
            reg["debatedor"]=df.iloc[i]["debatedor"]
            reg["articulador"]=df.iloc[i]["articulador"]
            reg["formulador"]=df.iloc[i]["formulador"]
            reg["negociador"]=df.iloc[i]["negociador"]
            print("Nome: {}, Estado: {}, Partido: {} cargo: {}".format(reg["nome"],reg["estado"],
                                                                       reg["partido"],
                                                                       reg["cargo"]))
            lista.append(reg)
        i+=1
    return lista

In [12]:
pag_18["debatedor"][pag_18["debatedor"]!="X"]=0
pag_18["debatedor"][pag_18["debatedor"]=="X"]=1
pag_18["articulador"][pag_18["articulador"]!="X"]=0
pag_18["articulador"][pag_18["articulador"]=="X"]=1
pag_18["formulador"][pag_18["formulador"]!="X"]=0
pag_18["formulador"][pag_18["formulador"]=="X"]=1
pag_18["negociador"][pag_18["negociador"]!="X"]=0
pag_18["negociador"][pag_18["negociador"]=="X"]=1
pag_18.head()

/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/home/carlos/anaconda3/envs/R/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cargo,Nome-partido,profissão,mandatos,cabeças,debatedor,articulador,formulador,negociador
0,NaN,PERNAMBUCO,NaN,NaN,NaN,0,0,0,0
1,DEPUTADO,ANDRÉ DE PAULA - PSD ADVOGADO,NaN,6o,1.0,0,1,0,0
2,DEPUTADO,ANDRÉ FERREIRA - PSC EMPRESÁRIO,NaN,1o,1.0,0,0,0,1
3,DEPUTADO,AUGUSTO COUTINHO - SOLIDARIEDADE ENGENHEIRO CIVIL,NaN,3o,1.0,0,0,0,1
4,DEPUTADO,DANIEL COELHO - CIDADANIA EMPRESÁRIO,NaN,2o,1.0,0,1,0,0

In [13]:
lista_pag_18=cria_lista_2(pag_18)

PERNAMBUCO
Nome: André De Paula, Estado: PERNAMBUCO, Partido: PSD cargo: Deputado
Nome: André Ferreira, Estado: PERNAMBUCO, Partido: PSC cargo: Deputado
Nome: Augusto Coutinho, Estado: PERNAMBUCO, Partido: SOLIDARIEDADE cargo: Deputado
Nome: Daniel Coelho, Estado: PERNAMBUCO, Partido: CIDADANIA cargo: Deputado
Nome: Danilo Cabral, Estado: PERNAMBUCO, Partido: PSB cargo: Deputado
Nome: Fernando Bezerra Coelho, Estado: PERNAMBUCO, Partido: MDB cargo: Senador
Nome: Humberto Costa, Estado: PERNAMBUCO, Partido: PT cargo: Senador
Nome: Renildo Calheiros, Estado: PERNAMBUCO, Partido: PCdoB cargo: Deputado
Nome: Silvio Costa Filho, Estado: PERNAMBUCO, Partido: PRB cargo: Deputado
Nome: Tadeu Alencar, Estado: PERNAMBUCO, Partido: PSB cargo: Deputado
PIAUÍ
Nome: Ciro Nogueira, Estado: PIAUÍ, Partido: PP cargo: Senador
Nome: Marcelo Castro, Estado: PIAUÍ, Partido: MDB cargo: Senador
RIO DE JANEIRO
Nome: Alessandro Molon, Estado: RIO DE JANEIRO, Partido: PSB cargo: Deputado
Nome: Aureo Ribeiro, Estado: RIO DE JANEIRO, Partido: SOLIDARIEDADE cargo: Deputado
Nome: Flávio Bolsonaro, Estado: RIO DE JANEIRO, Partido: PSL cargo: Senador
Nome: Glauber Braga, Estado: RIO DE JANEIRO, Partido: PSol cargo: Deputado
Nome: Jandira Feghali, Estado: RIO DE JANEIRO, Partido: PCdoB cargo: Deputada
Nome: Marcelo Freixo, Estado: RIO DE JANEIRO, Partido: PSOL cargo: Deputado
Nome: Rodrigo Maia, Estado: RIO DE JANEIRO, Partido: DEM cargo: Deputado
RIO GRANDE DO NORTE
RIO GRANDE DO SUL
Nome: Afonso Motta, Estado: RIO GRANDE DO SUL, Partido: PDT cargo: Deputado
Nome: Alceu Moreira, Estado: RIO GRANDE DO SUL, Partido: MDB cargo: Deputado
Nome: Darcísio Perondi, Estado: RIO GRANDE DO SUL, Partido: MDB cargo: Deputado
Nome: Henrique Fontana, Estado: RIO GRANDE DO SUL, Partido: PT cargo: Deputado
Nome: Marcel Van Hattem, Estado: RIO GRANDE DO SUL, Partido: NOVO cargo: Deputado
Nome: Paulo Paim, Estado: RIO GRANDE DO SUL, Partido: PT cargo: Senador
Nome: Paulo Pimenta, Estado: RIO GRANDE DO SUL, Partido: PT cargo: Deputado
RONDÔNIA
Nome: Marcos Rogério, Estado: RONDÔNIA, Partido: DEM cargo: Senador
RORAIMA
SANTA CATARINA
Nome: Carmen Zanotto, Estado: SANTA CATARINA, Partido: CIDADANIA cargo: Deputada
Nome: Espiridião Amin, Estado: SANTA CATARINA, Partido: PP cargo: Senador
SÃO PAULO
Nome: Alexandre Padilha, Estado: SÃO PAULO, Partido: PT cargo: Deputado
Nome: Arlindo Chinaglia, Estado: SÃO PAULO, Partido: PT cargo: Deputado
Nome: Arnaldo Jardim, Estado: SÃO PAULO, Partido: CIDADANIA cargo: Deputado
Nome: Baleia Rossi, Estado: SÃO PAULO, Partido: MDB cargo: Deputado
Nome: Carlos Sampaio, Estado: SÃO PAULO, Partido: PSDB cargo: Deputado
Nome: Carlos Zarattini, Estado: SÃO PAULO, Partido: PT cargo: Deputado
Nome: Eduardo Bolsonaro, Estado: SÃO PAULO, Partido: PSL cargo: Deputado
Nome: Eduardo Cury, Estado: SÃO PAULO, Partido: PSDB cargo: Deputado
Nome: Ivan Valente, Estado: SÃO PAULO, Partido: PSol cargo: Deputado
Nome: Joice Hasselmann, Estado: SÃO PAULO, Partido: PSL cargo: Deputada
Nome: José Serra, Estado: SÃO PAULO, Partido: PSDB cargo: Senador
Nome: Kim Kataguiri, Estado: SÃO PAULO, Partido: DEM cargo: Deputado
Nome: Luiza Erundina, Estado: SÃO PAULO, Partido: PSol cargo: Deputada
Nome: Major Olímpio, Estado: SÃO PAULO, Partido: PSL cargo: Senador
Nome: Marcos Pereira, Estado: SÃO PAULO, Partido: PRB cargo: Deputado
Nome: Orlando Silva, Estado: SÃO PAULO, Partido: PCdoB cargo: Deputado
Nome: Paulo Pereira Da Silva, Estado: SÃO PAULO, Partido: Solidariedade cargo: Deputado
Nome: Paulo Teixeira, Estado: SÃO PAULO, Partido: PT cargo: Deputado
Nome: Rui Falcão, Estado: SÃO PAULO, Partido: PT cargo: Deputado
Nome: Samuel Moreira, Estado: SÃO PAULO, Partido: PSDB cargo: Deputado
Nome: Tabata Amaral, Estado: SÃO PAULO, Partido: PDT cargo: Deputada
SERGIPE
Nome: Laercio Oliveira, Estado: SERGIPE, Partido: PP cargo: Deputado
Nome: Rogério Carvalho, Estado: SERGIPE, Partido: PT cargo: Senador
TOCANTINS
Nome: Eduardo Gomes, Estado: TOCANTINS, Partido: MDB cargo: Senador

In [14]:
lista_full=[]
lista_full=lista_pag_17+lista_pag_18
len(lista_full)
politicos_diap=pd.DataFrame(lista_full)
politicos_diap.head()

100

,nome,partido,cargo,estado,profissão,mandatos,cabeças,debatedor,articulador,formulador,negociador
0,Sérgio Petecão,PSD,Senador,ACRE,Empresário,1,1.0,0,1,0,0
1,Arthur Lira,PP,Deputado,ALAGOAS,Empresário,3,3.0,0,1,0,0
2,Renan Calheiros,MDB,Senador,ALAGOAS,Produtor Rural,4,23.0,0,1,0,0
3,Davi Alcolumbre,DEM,Senador,AMAPÁ,Comerciante,1,1.0,0,1,0,0
4,Randolfe Rodrigues,REDE,Senador,AMAPÁ,Professor,2,9.0,1,0,0,0

In [15]:
politicos_diap.to_csv('../dados/diap/politicos_diap.csv', index=False)

In [ ]:
x="6o"
x[0]