In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity="all"

In [2]:
!ls ../dados/tse

 BWEB_1t_RJ_101020181938.zip  'Dados Brutos'
 bweb_1t_RJ_101020182014.csv  'Dados Brutos-20200621T222156Z-001.zip'
 candidatos2014.csv	       leiame-boletimurnaweb.pdf
 candidatos2018.csv	       leiame.pdf
 consulta_cand_2018.zip

# Base de parlamentares

## 2018 deputados e senadores

In [3]:
df_parlamentares=pd.read_csv("../dados/tse/candidatos2018.csv", encoding="Latin 1",header=0)

In [4]:
#df_parlamentares.shape
#df_parlamentares.info()

In [5]:
#df_parlamentares.columns

In [6]:
df_parlamentares=df_parlamentares.drop(columns=['Unnamed: 0',"SQ_CANDIDATO", "NM_SOCIAL_CANDIDATO",'ANO_ELEICAO', 
                    'TP_ABRANGENCIA',
                    'NM_EMAIL', 'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
                    'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND', 'TP_AGREMIACAO',
                    'SQ_COLIGACAO','NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO', 'CD_NACIONALIDADE',
                    'DS_NACIONALIDADE', 'SG_UF_NASCIMENTO', 'CD_MUNICIPIO_NASCIMENTO',
                    'NM_MUNICIPIO_NASCIMENTO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE',
                    'NR_TITULO_ELEITORAL_CANDIDATO', 'CD_GENERO', 'DS_GENERO',
                    'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO', 'CD_ESTADO_CIVIL',
                    'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA', 'CD_OCUPACAO',
                    'DS_OCUPACAO', 'NR_DESPESA_MAX_CAMPANHA', 'CD_SIT_TOT_TURNO',
                    'DS_SIT_TOT_TURNO', 'ST_REELEICAO', 'ST_DECLARAR_BENS',
                    'NR_PROTOCOLO_CANDIDATURA', 'NR_PROCESSO '])
df_parlamentares.shape
#df_parlamentares.head()

(565, 10)

In [7]:
lista_uf=list(df_parlamentares["SG_UF"].unique())
#lista_uf=[]
#lista_uf.append("RJ")
lista_uf
df_mapa_geral=pd.DataFrame()
campos=["NR_CPF_CANDIDATO","NR_CANDIDATO","SG_UF"]

['RJ',
 'RS',
 'CE',
 'BA',
 'SP',
 'ES',
 'MG',
 'PA',
 'MT',
 'GO',
 'AL',
 'PR',
 'SE',
 'SC',
 'PE',
 'PB',
 'MA',
 'PI',
 'DF',
 'TO',
 'MS',
 'AC',
 'AP',
 'RN',
 'RR',
 'AM',
 'RO']

In [8]:
for uf in lista_uf:
    df_parl_uf=df_parlamentares[campos][df_parlamentares["SG_UF"]==uf]
    n_parlamentares=df_parl_uf.shape[0]
    arq="../dados/tse/Dados Brutos/votação/votacao_secao_2018_"+uf+".csv"
    print(arq)
    df=pd.read_csv(arq, encoding="Latin 1", sep=";",header=0)
    i=0
    while i < n_parlamentares:
        numero=df_parl_uf.iloc[i]["NR_CANDIDATO"]
        cpf=df_parl_uf.iloc[i]["NR_CPF_CANDIDATO"]
        df_votavel=df[df["NR_VOTAVEL"]==numero]
        mapa=df_votavel.groupby("NR_ZONA")["QT_VOTOS"].sum()
        parlamentar=pd.DataFrame(mapa, index=None)
        parlamentar["NR_CANDIDATO"]=numero
        parlamentar["NR_CPF_CANDIDATO"]=cpf
        parlamentar["SG_UF"]=uf
        parlamentar.reset_index(inplace=True)
        df_mapa_geral= df_mapa_geral.append(parlamentar, ignore_index = True)
        print("Número: {}, Votos: {}".format(numero,mapa.sum()))
        i+=1

../dados/tse/Dados Brutos/votação/votacao_secao_2018_RJ.csv
Número: 1716, Votos: 34274
Número: 1777, Votos: 204048
Número: 1033, Votos: 63952
Número: 1516, Votos: 54573
Número: 1717, Votos: 115119
Número: 1789, Votos: 41307
Número: 1767, Votos: 47065
Número: 1177, Votos: 103745
Número: 555, Votos: 2382265
Número: 5593, Votos: 196959
Número: 3100, Votos: 28216
Número: 9044, Votos: 35131
Número: 5077, Votos: 107317
Número: 4040, Votos: 227914
Número: 1515, Votos: 57707
Número: 177, Votos: 4380418
Número: 5510, Votos: 63561
Número: 1545, Votos: 136286
Número: 2050, Votos: 120498
Número: 2500, Votos: 45087
Número: 5050, Votos: 342491
Número: 1746, Votos: 57611
Número: 1752, Votos: 46934
Número: 1720, Votos: 345234
Número: 6565, Votos: 71646
Número: 1798, Votos: 62089
Número: 1377, Votos: 44804
Número: 1010, Votos: 65868
Número: 5005, Votos: 24295
Número: 1796, Votos: 31789
Número: 7070, Votos: 25817
Número: 5080, Votos: 40199
Número: 2727, Votos: 50284
Número: 2269, Votos: 55367
Número: 7733, Votos: 68414
Número: 2323, Votos: 50533
Número: 5570, Votos: 37526
Número: 2501, Votos: 56646
Número: 2222, Votos: 48328
Número: 2587, Votos: 74232
Número: 2577, Votos: 94203
Número: 1234, Votos: 25557
Número: 1714, Votos: 38525
Número: 3030, Votos: 52983
Número: 1155, Votos: 47101
Número: 1793, Votos: 104211
Número: 1210, Votos: 26417
Número: 4488, Votos: 39398
../dados/tse/Dados Brutos/votação/votacao_secao_2018_RS.csv
Número: 1111, Votos: 102063
Número: 1200, Votos: 65712
Número: 4041, Votos: 52977
Número: 1700, Votos: 91664
Número: 4500, Votos: 74789
Número: 1777, Votos: 32200
Número: 5501, Votos: 102662
Número: 1500, Votos: 100341
Número: 1720, Votos: 88559
Número: 131, Votos: 1875245
Número: 4012, Votos: 109053
Número: 1144, Votos: 97163
Número: 1307, Votos: 133086
Número: 1412, Votos: 69904
Número: 1477, Votos: 83617
Número: 1355, Votos: 122838
Número: 1313, Votos: 108585
Número: 1133, Votos: 89707
Número: 1166, Votos: 100018
Número: 1212, Votos: 80427
Número: 2222, Votos: 151719
Número: 4511, Votos: 114346
Número: 1520, Votos: 100362
Número: 2522, Votos: 183518
Número: 1522, Votos: 86305
Número: 1515, Votos: 93088
Número: 1010, Votos: 103373
Número: 5050, Votos: 114302
Número: 1208, Votos: 116483
Número: 1320, Votos: 102964
Número: 111, Votos: 2316365
Número: 1370, Votos: 97303
Número: 3030, Votos: 349855
../dados/tse/Dados Brutos/votação/votacao_secao_2018_CE.csv
Número: 1213, Votos: 154338
Número: 5555, Votos: 111154
Número: 1234, Votos: 103385
Número: 900, Votos: 1325786
Número: 1515, Votos: 128526
Número: 1322, Votos: 173039
Número: 1221, Votos: 157510
Número: 1313, Votos: 173777
Número: 1111, Votos: 132319
Número: 1214, Votos: 87009
Número: 1717, Votos: 97201
Número: 9090, Votos: 303593
Número: 123, Votos: 3228533
Número: 4000, Votos: 106294
Número: 1212, Votos: 102417
Número: 1233, Votos: 131275
Número: 2277, Votos: 65300
Número: 1451, Votos: 119030
Número: 9099, Votos: 30392
Número: 1333, Votos: 74099
Número: 5151, Votos: 67917
Número: 7777, Votos: 113515
Número: 4580, Votos: 102470
Número: 4321, Votos: 208854
../dados/tse/Dados Brutos/votação/votacao_secao_2018_BA.csv
Número: 7000, Votos: 323264
Número: 555, Votos: 3927598
Número: 4040, Votos: 104348
Número: 1323, Votos: 129196
Número: 2288, Votos: 84684
Número: 3111, Votos: 54858
Número: 4545, Votos: 102603
Número: 1144, Votos: 118097
Número: 130, Votos: 4253331
Número: 1717, Votos: 136742
Número: 1025, Votos: 84455
Número: 5400, Votos: 66343
Número: 1313, Votos: 135657
Número: 1919, Votos: 149274
Número: 1234, Votos: 91913
Número: 1310, Votos: 118313
Número: 5577, Votos: 99535
Número: 4000, Votos: 115277
Número: 6522, Votos: 126595
Número: 5580, Votos: 105427
Número: 1346, Votos: 101476
Número: 2526, Votos: 84090
Número: 1301, Votos: 130548
Número: 2552, Votos: 103823
Número: 1122, Votos: 104322
Número: 2512, Votos: 88908
Número: 1322, Votos: 121278
Número: 5511, Votos: 74116
Número: 5588, Votos: 185428
Número: 5510, Votos: 127716
Número: 6565, Votos: 114213
Número: 1312, Votos: 115571
Número: 1010, Votos: 95204
Número: 1111, Votos: 102512
Número: 1223, Votos: 62922
Número: 2222, Votos: 84016
Número: 1115, Votos: 106592
Número: 4422, Votos: 38829
Número: 2525, Votos: 82110
Número: 3100, Votos: 50345
Número: 7070, Votos: 48899
../dados/tse/Dados Brutos/votação/votacao_secao_2018_SP.csv
Número: 4077, Votos: 106100
Número: 1920, Votos: 239784
Número: 5000, Votos: 249887
Número: 2345, Votos: 132363
Número: 1123, Votos: 118684
Número: 1200, Votos: 264450
Número: 1022, Votos: 71745
Número: 2550, Votos: 89378
Número: 1701, Votos: 69256
Número: 1055, Votos: 77413
Número: 1390, Votos: 70645
Número: 6565, Votos: 64822
Número: 1358, Votos: 67892
Número: 1771, Votos: 1078666
Número: 4580, Votos: 103215
Número: 2244, Votos: 75218
Número: 1720, Votos: 1843735
Número: 1000, Votos: 521728
Número: 4336, Votos: 108038
Número: 2343, Votos: 127366
Número: 4585, Votos: 126847
Número: 4510, Votos: 120529
Número: 4515, Votos: 94282
Número: 1700, Votos: 98373
Número: 7777, Votos: 75613
Número: 1999, Votos: 56033
Número: 1322, Votos: 87449
Número: 1777, Votos: 155522
Número: 1515, Votos: 214042
Número: 1919, Votos: 161239
Número: 4015, Votos: 100179
Número: 4551, Votos: 102708
Número: 2277, Votos: 93093
Número: 2020, Votos: 91797
Número: 4500, Votos: 125666
Número: 4001, Votos: 86433
Número: 1770, Votos: 78712
Número: 2525, Votos: 116416
Número: 1100, Votos: 134301
Número: 1010, Votos: 139165
Número: 5021, Votos: 176883
Número: 1710, Votos: 76306
Número: 1790, Votos: 31718
Número: 2577, Votos: 92257
Número: 1111, Votos: 121869
Número: 1702, Votos: 118457
Número: 2200, Votos: 242327
Número: 2233, Votos: 109461
Número: 1353, Votos: 124281
Número: 1370, Votos: 137909
Número: 5500, Votos: 137628
Número: 1717, Votos: 74190
Número: 3000, Votos: 45298
Número: 3050, Votos: 64341
Número: 1085, Votos: 97862
Número: 2533, Votos: 99865
Número: 457, Votos: 6513282
Número: 3030, Votos: 207118
Número: 2555, Votos: 465310
Número: 5050, Votos: 155334
Número: 1313, Votos: 158389
Número: 1190, Votos: 119034
Número: 2222, Votos: 453855
Número: 1398, Votos: 78512
Número: 2299, Votos: 135844
Número: 2240, Votos: 264013
Número: 1354, Votos: 87576
Número: 5577, Votos: 119024
Número: 177, Votos: 9039717
Número: 4044, Votos: 99974
Número: 1078, Votos: 82097
Número: 1551, Votos: 49653
../dados/tse/Dados Brutos/votação/votacao_secao_2018_ES.csv
Número: 1350, Votos: 73384
Número: 2500, Votos: 57156
Número: 181, Votos: 1117036
Número: 1717, Votos: 57741
Número: 4040, Votos: 55957
Número: 4044, Votos: 84405
Número: 1010, Votos: 181813
Número: 2323, Votos: 74787
Número: 2222, Votos: 51983
Número: 1212, Votos: 73030
Número: 1143, Votos: 48412
Número: 234, Votos: 863359
../dados/tse/Dados Brutos/votação/votacao_secao_2018_MG.csv
Número: 1378, Votos: 176841
Número: 4560, Votos: 80990
Número: 7777, Votos: 109335
Número: 5555, Votos: 105803
Número: 4055, Votos: 103533
Número: 1717, Votos: 230008
Número: 7070, Votos: 50474
Número: 5133, Votos: 87446
Número: 5544, Votos: 115795
Número: 2545, Votos: 87683
Número: 1363, Votos: 68686
Número: 1313, Votos: 131312
Número: 3031, Votos: 71901
Número: 5152, Votos: 60950
Número: 1314, Votos: 89378
Número: 3022, Votos: 64022
Número: 1999, Votos: 60509
Número: 4550, Votos: 131120
Número: 1707, Votos: 51073
Número: 1307, Votos: 87891
Número: 1333, Votos: 112724
Número: 1122, Votos: 98404
Número: 7011, Votos: 37620
Número: 1315, Votos: 131228
Número: 5505, Votos: 128537
Número: 4057, Votos: 70481
Número: 1111, Votos: 74223
Número: 1745, Votos: 51626
Número: 9033, Votos: 157394
Número: 1515, Votos: 120489
Número: 1704, Votos: 48043
Número: 1231, Votos: 93932
Número: 7040, Votos: 178660
Número: 1511, Votos: 58243
Número: 9090, Votos: 129199
Número: 1513, Votos: 63149
Número: 3333, Votos: 32833
Número: 4050, Votos: 58413
Número: 5018, Votos: 162740
Número: 1720, Votos: 158541
Número: 1312, Votos: 194332
Número: 1234, Votos: 89046
Número: 1777, Votos: 58176
Número: 250, Votos: 3616864
Número: 4545, Votos: 79797
Número: 1010, Votos: 162092
Número: 2233, Votos: 105731
Número: 1510, Votos: 69900
Número: 4535, Votos: 105969
Número: 1080, Votos: 103090
Número: 4500, Votos: 106702
Número: 2015, Votos: 65316
Número: 310, Votos: 3568658
Número: 3133, Votos: 107219
Número: 3132, Votos: 53390
../dados/tse/Dados Brutos/votação/votacao_secao_2018_PA.csv
Número: 2500, Votos: 135398
Número: 4011, Votos: 130768
Número: 1010, Votos: 158717
Número: 5050, Votos: 184042
Número: 2222, Votos: 176812
Número: 1313, Votos: 143822
Número: 200, Votos: 1374956
Número: 5555, Votos: 95582
Número: 2525, Votos: 102554
Número: 1456, Votos: 96722
Número: 1444, Votos: 75346
Número: 5500, Votos: 145653
Número: 1515, Votos: 165202
Número: 1555, Votos: 154647
Número: 4590, Votos: 148972
Número: 4567, Votos: 146288
Número: 1321, Votos: 106965
Número: 5588, Votos: 146678
Número: 151, Votos: 1383306
../dados/tse/Dados Brutos/votação/votacao_secao_2018_MT.csv
Número: 1122, Votos: 73072
Número: 7700, Votos: 52335
Número: 1313, Votos: 51015
Número: 1515, Votos: 59155
Número: 1900, Votos: 82528
Número: 1700, Votos: 126249
Número: 1414, Votos: 76781
Número: 1520, Votos: 49912
../dados/tse/Dados Brutos/votação/votacao_secao_2018_GO.csv
Número: 111, Votos: 1729637
Número: 2555, Votos: 96188
Número: 4599, Votos: 70663
Número: 2018, Votos: 100437
Número: 1170, Votos: 88545
Número: 2580, Votos: 151508
Número: 1313, Votos: 83063
Número: 5555, Votos: 111788
Número: 444, Votos: 1557415
Número: 1212, Votos: 169774
Número: 4444, Votos: 64941
Número: 7777, Votos: 78431
Número: 1701, Votos: 31190
Número: 4040, Votos: 74877
Número: 1919, Votos: 61809
Número: 1111, Votos: 77729
Número: 2222, Votos: 88894
Número: 1010, Votos: 106014
Número: 1700, Votos: 274406
../dados/tse/Dados Brutos/votação/votacao_secao_2018_AL.csv
Número: 4544, Votos: 44207
Número: 456, Votos: 895738
Número: 5555, Votos: 139458
Número: 151, Votos: 621562
Número: 1111, Votos: 143858
Número: 1010, Votos: 70413
Número: 1515, Votos: 71847
Número: 2222, Votos: 98201
Número: 1313, Votos: 60900
Número: 1400, Votos: 84956
Número: 4040, Votos: 178645
../dados/tse/Dados Brutos/votação/votacao_secao_2018_PR.csv
Número: 5569, Votos: 92399
Número: 1122, Votos: 75540
Número: 1234, Votos: 113252
Número: 1512, Votos: 94077
Número: 1540, Votos: 110717
Número: 1010, Votos: 52572
Número: 1313, Votos: 212513
Número: 1080, Votos: 141730
Número: 2222, Votos: 73344
Número: 1151, Votos: 80025
Número: 5555, Votos: 124512
Número: 1777, Votos: 241537
Número: 4040, Votos: 98214
Número: 5577, Votos: 70001
Número: 9000, Votos: 90158
Número: 2233, Votos: 107636
Número: 2505, Votos: 92300
Número: 191, Votos: 2957239
Número: 9090, Votos: 72475
Número: 1717, Votos: 33628
Número: 2200, Votos: 111384
Número: 4012, Votos: 95386
Número: 1700, Votos: 75326
Número: 4300, Votos: 123958
Número: 2300, Votos: 76471
Número: 1414, Votos: 90249
Número: 181, Votos: 2331740
Número: 1330, Votos: 62169
Número: 5590, Votos: 314963
Número: 2020, Votos: 118754
Número: 1919, Votos: 103154
Número: 1310, Votos: 77306
../dados/tse/Dados Brutos/votação/votacao_secao_2018_SE.csv
Número: 1111, Votos: 68014
Número: 7777, Votos: 64132
Número: 5555, Votos: 102899
Número: 1212, Votos: 35226
Número: 131, Votos: 300247
Número: 2090, Votos: 45472
Número: 181, Votos: 474449
Número: 1515, Votos: 64879
Número: 2233, Votos: 47788
Número: 1311, Votos: 59933
../dados/tse/Dados Brutos/votação/votacao_secao_2018_SC.csv
Número: 1762, Votos: 60069
Número: 1560, Votos: 80086
Número: 1133, Votos: 86189
Número: 5500, Votos: 68130
Número: 3050, Votos: 27443
Número: 2323, Votos: 84703
Número: 1718, Votos: 109363
Número: 1510, Votos: 76925
Número: 1350, Votos: 115232
Número: 1717, Votos: 142571
Número: 1777, Votos: 87345
Número: 5511, Votos: 61830
Número: 222, Votos: 1179757
Número: 4050, Votos: 43314
Número: 1010, Votos: 179307
Número: 4577, Votos: 101937
Número: 111, Votos: 1226064
Número: 1570, Votos: 97613
../dados/tse/Dados Brutos/votação/votacao_secao_2018_PE.csv
Número: 5555, Votos: 118641
Número: 3131, Votos: 52824
Número: 4040, Votos: 460387
Número: 2323, Votos: 97745
Número: 1310, Votos: 193108
Número: 2020, Votos: 175834
Número: 1314, Votos: 72005
Número: 1190, Votos: 82071
Número: 4000, Votos: 80498
Número: 4004, Votos: 114268
Número: 1111, Votos: 113640
Número: 1010, Votos: 109185
Número: 1234, Votos: 82592
Número: 4020, Votos: 53597
Número: 6513, Votos: 57919
Número: 7777, Votos: 77817
Número: 2501, Votos: 92188
Número: 1919, Votos: 73551
Número: 130, Votos: 1713565
Número: 1515, Votos: 87585
Número: 1212, Votos: 75642
Número: 4010, Votos: 91635
Número: 2233, Votos: 129978
Número: 156, Votos: 1430802
Número: 1717, Votos: 117943
Número: 5151, Votos: 125025
Número: 1012, Votos: 65939
../dados/tse/Dados Brutos/votação/votacao_secao_2018_PB.csv
Número: 111, Votos: 831701
Número: 4040, Votos: 146860
Número: 1212, Votos: 100876
Número: 2511, Votos: 76089
Número: 400, Votos: 844786
Número: 1345, Votos: 91408
Número: 2222, Votos: 107465
Número: 4500, Votos: 69935
Número: 1111, Votos: 120220
Número: 1411, Votos: 86208
Número: 1011, Votos: 92468
Número: 4510, Votos: 76754
Número: 1717, Votos: 71899
Número: 4567, Votos: 61259
../dados/tse/Dados Brutos/votação/votacao_secao_2018_MA.csv
Número: 6513, Votos: 134223
Número: 1313, Votos: 76893
Número: 1919, Votos: 105778
Número: 2200, Votos: 117033
Número: 3333, Votos: 189843
Número: 6565, Votos: 111584
Número: 1111, Votos: 105606
Número: 3344, Votos: 47757
Número: 1555, Votos: 67352
Número: 2510, Votos: 97075
Número: 123, Votos: 1997450
Número: 232, Votos: 1539942
Número: 1414, Votos: 111538
Número: 4000, Votos: 99598
Número: 1010, Votos: 101806
Número: 1234, Votos: 72038
Número: 5533, Votos: 106578
Número: 2222, Votos: 195768
Número: 5122, Votos: 79674
Número: 1513, Votos: 77661
../dados/tse/Dados Brutos/votação/votacao_secao_2018_PI.csv
Número: 1313, Votos: 129623
Número: 1122, Votos: 76338
Número: 1311, Votos: 138800
Número: 3636, Votos: 70828
Número: 1212, Votos: 111672
Número: 151, Votos: 812213
Número: 4040, Votos: 54095
Número: 1515, Votos: 73302
Número: 1111, Votos: 96277
Número: 111, Votos: 897959
Número: 2222, Votos: 132719
Número: 5555, Votos: 110804
../dados/tse/Dados Brutos/votação/votacao_secao_2018_DF.csv
Número: 2555, Votos: 65107
Número: 2345, Votos: 46069
Número: 1122, Votos: 31610
Número: 456, Votos: 403735
Número: 4417, Votos: 86415
Número: 4343, Votos: 67598
Número: 1331, Votos: 89986
Número: 2200, Votos: 121340
Número: 408, Votos: 467787
Número: 1010, Votos: 79775
../dados/tse/Dados Brutos/votação/votacao_secao_2018_TO.csv
Número: 2525, Votos: 48012
Número: 555, Votos: 214355
Número: 7788, Votos: 71842
Número: 1511, Votos: 40719
Número: 1303, Votos: 18167
Número: 2020, Votos: 58726
Número: 7700, Votos: 48812
Número: 2580, Votos: 48008
Número: 777, Votos: 248358
Número: 2222, Votos: 49868
../dados/tse/Dados Brutos/votação/votacao_secao_2018_MS.csv
Número: 144, Votos: 424085
Número: 5555, Votos: 89385
Número: 4545, Votos: 80500
Número: 4555, Votos: 120901
Número: 1707, Votos: 50376
Número: 1234, Votos: 40233
Número: 1733, Votos: 56339
Número: 1331, Votos: 55970
Número: 2525, Votos: 75068
Número: 177, Votos: 373712
../dados/tse/Dados Brutos/votação/votacao_secao_2018_AC.csv
Número: 1555, Votos: 18723
Número: 1212, Votos: 9537
Número: 1515, Votos: 28717
Número: 1010, Votos: 7489
Número: 2525, Votos: 22263
Número: 151, Votos: 185066
Número: 4545, Votos: 40047
Número: 555, Votos: 244109
Número: 7777, Votos: 22219
Número: 6513, Votos: 18374
../dados/tse/Dados Brutos/votação/votacao_secao_2018_AP.csv
Número: 4040, Votos: 24987
Número: 1111, Votos: 12856
Número: 7070, Votos: 11301
Número: 147, Votos: 128186
Número: 9000, Votos: 19111
Número: 4545, Votos: 14069
Número: 2222, Votos: 18818
Número: 180, Votos: 264798
Número: 1000, Votos: 16519
Número: 6565, Votos: 14196
../dados/tse/Dados Brutos/votação/votacao_secao_2018_RN.csv
Número: 313, Votos: 660315
Número: 1311, Votos: 112998
Número: 2222, Votos: 93505
Número: 1777, Votos: 81640
Número: 5555, Votos: 70350
Número: 4040, Votos: 82791
Número: 180, Votos: 745827
Número: 3666, Votos: 125841
Número: 1511, Votos: 79333
Número: 1111, Votos: 71092
../dados/tse/Dados Brutos/votação/votacao_secao_2018_RR.csv
Número: 255, Votos: 111466
Número: 2200, Votos: 11952
Número: 7777, Votos: 11879
Número: 107, Votos: 85366
Número: 1111, Votos: 13299
Número: 1818, Votos: 8491
Número: 1717, Votos: 12969
Número: 1011, Votos: 13429
Número: 5555, Votos: 14751
Número: 4545, Votos: 12129
../dados/tse/Dados Brutos/votação/votacao_secao_2018_AM.csv
Número: 5555, Votos: 77458
Número: 2222, Votos: 106805
Número: 1717, Votos: 151649
Número: 1111, Votos: 118700
Número: 155, Votos: 607286
Número: 7777, Votos: 55477
Número: 1313, Votos: 197270
Número: 1010, Votos: 117181
Número: 1000, Votos: 107168
Número: 455, Votos: 834809
../dados/tse/Dados Brutos/votação/votacao_secao_2018_RO.csv
Número: 1234, Votos: 33038
Número: 4545, Votos: 38776
Número: 255, Votos: 324939
Número: 1555, Votos: 38630
Número: 1111, Votos: 34193
Número: 1919, Votos: 69565
Número: 4040, Votos: 30399
Número: 5555, Votos: 39953
Número: 152, Votos: 230361
Número: 1777, Votos: 28344

In [9]:
uf

'RO'

In [10]:
df_mapa_geral.shape

(90762, 5)

In [11]:
df_mapa_geral.head()

   NR_ZONA  QT_VOTOS  NR_CANDIDATO  NR_CPF_CANDIDATO SG_UF
0        4        42          1716         413473740    RJ
1        5        66          1716         413473740    RJ
2        7        61          1716         413473740    RJ
3        8        84          1716         413473740    RJ
4        9        97          1716         413473740    RJ

In [12]:
df_mapa_geral.tail()

       NR_ZONA  QT_VOTOS  NR_CANDIDATO  NR_CPF_CANDIDATO SG_UF
90757       29      1048          1777       70335591787    RO
90758       30       865          1777       70335591787    RO
90759       32       354          1777       70335591787    RO
90760       34       648          1777       70335591787    RO
90761       35       173          1777       70335591787    RO

In [13]:
df_mapa_geral.to_csv("../dados/tse/mapa_geral.csv")