# Normalizaçãodos dados

In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import sqlite3 as sql
import seaborn as sns
import csv
import squarify 
from unidecode import unidecode
import os

from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity="all"

# Tratamento dados TSE

In [2]:
!ls ../dados/tse/dados_limpos

detalhes_municipios.csv  detalhes_parlamentares.csv  output_voto_legenda.csv

### Tratamento dados parlamentares - cadastro base

In [3]:
#Dados de parlamentares
#enc="ISO-8859-3"
enc="Latin 1"
df_parlamentares=pd.read_csv("../dados/tse/dados_limpos/detalhes_parlamentares.csv", 
                             encoding=enc,
                             dtype={"NR_CPF_CANDIDATO":"object"},
                             header=0)

In [4]:
#df_parlamentares.sample(5)

In [5]:
#renomeando CPF
df_parlamentares.rename(columns={"NR_CPF_CANDIDATO":"CPF"}, inplace=True)
#df_parlamentares.info()

In [6]:
#df_parlamentares.columns

In [7]:
#Criando cadastro de parlamentares
df_parl_cadastro=df_parlamentares.copy()

In [8]:
# Drop nas colunas desnecessárias
df_parl_cadastro=df_parl_cadastro.drop(["DS_SIT_TOT_TURNO",'ST_REELEICAO',
                                        'ST_DECLARAR_BENS', 'CD_TIPO_BEM_CANDIDATO',
                                        'DS_TIPO_BEM_CANDIDATO', 'DS_BEM_CANDIDATO', 
                                        'VR_BEM_CANDIDATO'], axis=1)

In [9]:
# retirando linhas duplicadas do cadastro
df_parl_cadastro.drop_duplicates(inplace=True)
df_parl_cadastro.reset_index(drop=True, inplace=True)
#df_parl_cadastr.shape
#df_parl_cadastro.column

### Tratamento bens de parlamentares

In [10]:
#Criando tabela de bens de parmanetares
df_parl_bens=df_parlamentares.copy()
df_parl_bens=df_parl_bens.drop(["DS_SIT_TOT_TURNO",'ST_REELEICAO',"ANO_ELEICAO",
                                'SG_UE', 'DS_CARGO', 'SQ_CANDIDATO', 'NM_CANDIDATO',
                                'NM_URNA_CANDIDATO','NM_EMAIL', 'SG_PARTIDO',
                                'SG_UF_NASCIMENTO', 'NM_MUNICIPIO_NASCIMENTO', 
                                'DT_NASCIMENTO','NR_IDADE_DATA_POSSE', 'DS_GENERO',
                                'DS_GRAU_INSTRUCAO','DS_ESTADO_CIVIL', 'DS_COR_RACA', 
                                'DS_OCUPACAO', 'DS_SIT_TOT_TURNO','ST_REELEICAO'], 
                               axis=1)
df_parl_bens.reset_index(inplace=True, drop=True)
#df_parl_bens.shape
#df_parl_bens.info()

### Ajustando cadastro base com os bens dos parlamentares

In [11]:
# Criando valor total de bens dos parlamentares e colocando no cadastro
df_parl_cadastro["VL_BENS"]=0.
i=0
nparl=df_parl_cadastro.shape[0]
while i < nparl:
    cpf=df_parl_cadastro.iloc[i]["CPF"]
    total=df_parl_bens[df_parl_bens["CPF"]==cpf]["VR_BEM_CANDIDATO"].sum()
    #print("i-> {} CPF: {}, Valor: {}".format(i,cpf,total))
    #vl_bens[i]=total
    df_parl_cadastro.loc[i,"VL_BENS"]=total
    i+=1

In [12]:
#df_parl_cadastro.sample(5)

In [13]:
#Reordenando colunas
df_parl_cadastro=df_parl_cadastro[["CPF","NM_CANDIDATO","DT_NASCIMENTO","SG_UF_NASCIMENTO",
                  "NM_MUNICIPIO_NASCIMENTO", "DS_GENERO", "DS_GRAU_INSTRUCAO",
                  "DS_ESTADO_CIVIL", "DS_COR_RACA", "DS_OCUPACAO","VL_BENS",
                  "ANO_ELEICAO", "DS_CARGO", "SG_PARTIDO","SG_UE","SQ_CANDIDATO","NM_URNA_CANDIDATO",
                    "NR_IDADE_DATA_POSSE",'NM_EMAIL']]

In [14]:
df_parl_cadastro["NM_URNA_CANDIDATO"]=df_parl_cadastro["NM_URNA_CANDIDATO"].apply(lambda x:unidecode(x))

In [15]:
df_parl_cadastro.sample(5)

,CPF,NM_CANDIDATO,DT_NASCIMENTO,SG_UF_NASCIMENTO,NM_MUNICIPIO_NASCIMENTO,DS_GENERO,DS_GRAU_INSTRUCAO,DS_ESTADO_CIVIL,DS_COR_RACA,DS_OCUPACAO,VL_BENS,ANO_ELEICAO,DS_CARGO,SG_PARTIDO,SG_UE,SQ_CANDIDATO,NM_URNA_CANDIDATO,NR_IDADE_DATA_POSSE,NM_EMAIL
286,95622780772,MARCELO RIBEIRO FREIXO,12/04/1967,RJ,SAO GONÃALO,MASCULINO,SUPERIOR COMPLETO,DIVORCIADO(A),BRANCA,DEPUTADO,13918.01,2018,DEPUTADO FEDERAL,PSOL,RJ,190000602109,MARCELO FREIXO,51.0,GLORIA@VIVEIROS.ADV.BR
25,01124552049,LASIER COSTA MARTINS,14/04/1942,RS,GENERAL CAMARA,MASCULINO,SUPERIOR COMPLETO,DIVORCIADO(A),BRANCA,JORNALISTA E REDATOR,1999326.91,2014,SENADOR,PDT,RS,210000000283,LASIER MARTINS,72.0,LASIER@TERRA.COM.BR
429,50903691434,DANILO JORGE DE BARROS CABRAL,21/04/1967,PE,SURUBIM,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,DEPUTADO,949277.88,2018,DEPUTADO FEDERAL,PSB,PE,170000610278,DANILO CABRAL,51.0,DEP.DANILOCABRAL@CAMARA.LEG.BR
391,63223228268,LUIZ CARLOS GOMES DOS SANTOS JUNIOR,16/08/1979,AP,AMAPA,MASCULINO,SUPERIOR COMPLETO,DIVORCIADO(A),BRANCA,ADVOGADO,60000.00,2018,DEPUTADO FEDERAL,PSDB,AP,30000617195,LUIZ CARLOS,39.0,XLUIZJUNIOR@HOTMAIL.COM
254,20040954072,PEDRO BANDARRA WESTPHALEN,19/12/1950,RS,CRUZ ALTA,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,DEPUTADO,1267305.69,2018,DEPUTADO FEDERAL,PP,RS,210000604834,PEDRO WESTPHALEN,68.0,PEDROWESTPHALEN@GMAIL.COM

### Dados de votação nos municípios

In [16]:
#Dados de municipios e votacão
enc="ISO-8859-1"
#enc="Latin 1"
df_municipios=pd.read_csv("../dados/tse/dados_limpos/detalhes_municipios.csv", 
                             encoding=enc,
                            dtype={"NR_CPF_CANDIDATO":"object"},
                             header=0)

In [17]:
#renomeando CPF
df_municipios.rename(columns={"NR_CPF_CANDIDATO":"CPF"}, inplace=True)
#df_municipios.head(5)
#df_municipios.info()

In [18]:

#df_municipios.columns

In [19]:
df_parl_votacao=df_municipios[["CPF", "SG_UF", "CD_MUNICIPIO",
                            "VOTOS_TOTAL_MUN", 'CODIGO_IBGE']].copy()
df_parl_votacao.reset_index(inplace=True, drop=True)

In [20]:
#df_parl_votacao.head()

In [21]:
df_votacao=df_parl_cadastro[["CPF","DS_CARGO", "SG_PARTIDO","SG_UE"]].copy()
df_votacao.reset_index(inplace=True, drop=True)
df_votacao=pd.merge(df_votacao, df_parl_votacao, how="left", on="CPF")

In [22]:
#df_votacao.shape
#df_votacao.head()
df_votacao.head(5)

,CPF,DS_CARGO,SG_PARTIDO,SG_UE,SG_UF,CD_MUNICIPIO,VOTOS_TOTAL_MUN,CODIGO_IBGE
0,23019093104,SENADOR,PR,MT,MT,90042,1062,5100359.0
1,23019093104,SENADOR,PR,MT,MT,90166,1013,5108857.0
2,23019093104,SENADOR,PR,MT,MT,98337,2092,5103452.0
3,23019093104,SENADOR,PR,MT,MT,90670,113036,5103403.0
4,23019093104,SENADOR,PR,MT,MT,90905,1429,5101852.0

### Tabela consolidando votação dos partidos nos municípios (parlamentares)

In [23]:
df_partidos_votacao=df_votacao.groupby(["SG_PARTIDO","SG_UF","DS_CARGO","CODIGO_IBGE"], 
                                      as_index=False)["VOTOS_TOTAL_MUN"].sum()
df_partidos_votacao.shape

(94846, 5)

In [24]:
df_partidos_votacao.head()

  SG_PARTIDO SG_UF          DS_CARGO  CODIGO_IBGE  VOTOS_TOTAL_MUN
0     AVANTE    AP  DEPUTADO FEDERAL    1600055.0               74
1     AVANTE    AP  DEPUTADO FEDERAL    1600105.0               89
2     AVANTE    AP  DEPUTADO FEDERAL    1600154.0              478
3     AVANTE    AP  DEPUTADO FEDERAL    1600204.0               22
4     AVANTE    AP  DEPUTADO FEDERAL    1600212.0               53

In [25]:
# Código com groupby para consolidar votação
#df_partido=df_partidos_votacao[df_partidos_votacao["SG_PARTIDO"]=="PSOL"]
#df_partido.groupby("SG_UF",as_index=False)["VOTOS_TOTAL_MUN"].sum().sort_values("VOTOS_TOTAL_MUN",ascending=False)

### Tabela consolidando votos em legenda nos municípios (legenda)

In [26]:
#Dados de municipios e votacão
enc="ISO-8859-1"
#enc="Latin 1"
df_legenda=pd.read_csv("../dados/tse/dados_limpos/output_voto_legenda.csv", 
                             encoding=enc,
                             sep=";",
                             header=0)

In [27]:
#df_legenda.head()
#df_legenda.shape

In [28]:
df_legendas_votacao=df_legenda.groupby(["SG_PARTIDO","SG_UF","DS_CARGO","CODIGO_IBGE"], 
                                      as_index=False)["VOTOS_TOTAL_MUN"].sum()
#df_legendas_votacao.shape
#df_legendas_votacao.head(5)

In [29]:
df_legendas_votacao["DS_CARGO"]=df_legendas_votacao["DS_CARGO"].apply(lambda x:x.upper())
df_legendas_votacao.sample(5)

       SG_PARTIDO SG_UF          DS_CARGO  CODIGO_IBGE  VOTOS_TOTAL_MUN
62248         PDT    PI  DEPUTADO FEDERAL    2204204.0               38
33630        NOVO    PR  DEPUTADO FEDERAL    4107108.0                1
102709        PPL    SE  DEPUTADO FEDERAL    2807303.0                0
198336         PT    BA           SENADOR    2913903.0                0
206482         PT    SP  DEPUTADO FEDERAL    3538501.0               24

### Tabela cadastro com informações dos municípios

In [30]:
df_municipios=df_municipios[['CODIGO_IBGE','SG_UF','NM_MUNICIPIO',
                          'IDHM_2010', 'IDHM_RENDA_2010',
                          'IDHM_LONGEV_2010','IDHM_EDUC_2010']].copy()
df_municipios.drop_duplicates(inplace=True)
df_municipios.sort_values(["SG_UF","NM_MUNICIPIO"], inplace=True)
df_municipios.reset_index(inplace=True, drop=True)
df_municipios.head()

,CODIGO_IBGE,SG_UF,NM_MUNICIPIO,IDHM_2010,IDHM_RENDA_2010,IDHM_LONGEV_2010,IDHM_EDUC_2010
0,1200013.0,AC,ACRELANDIA,0.604,0.584,0.808,0.466
1,1200054.0,AC,ASSIS BRASIL,0.588,0.578,0.770,0.456
2,1200104.0,AC,BRASILEIA,0.614,0.619,0.770,0.485
3,1200138.0,AC,BUJARI,0.589,0.603,0.772,0.439
4,1200179.0,AC,CAPIXABA,0.575,0.601,0.794,0.398

## Salvando bases TSE em base sql

### Abrindo base sql

In [31]:
con = sql.connect("../dados/sql/base_completa.db")

### Salvando tabelas

In [32]:
df_parl_cadastro.to_sql("cadastro",con,if_exists="replace", index=False, index_label="CPF")
df_parl_bens.to_sql("parl_bens",con,if_exists="replace", index=False, index_label="CPF")
df_parl_votacao.to_sql("parl_votacao",con,if_exists="replace", index=False, index_label="CPF")
df_partidos_votacao.to_sql("partidos_votacao",con,if_exists="replace", index=False, index_label="SG_PARTIDO")
df_legendas_votacao.to_sql("legendas_votacao",con,if_exists="replace", index=False, index_label="SG_PARTIDO")
df_municipios.to_sql("municipios",con,if_exists="replace", index=False, index_label="CODIGO_IBGE")

### fechando base sql

In [33]:
con.close()

# Tratando diap

In [34]:
df_diap=pd.read_csv("../dados/diap/politicos_diap_cpf.csv", dtype={"CPF":"object"})
#df_diap.info()

In [35]:
df_diap.drop(columns=["nome","partido","cargo","estado","profissão"], inplace=True)
#df_diap.info()

In [36]:
df_diap=df_diap[["CPF","mandatos","cabeças","debatedor","articulador","formulador","negociador"]].copy()
df_diap.head()

,CPF,mandatos,cabeças,debatedor,articulador,formulador,negociador
0,09604332287,1,1.0,0,1,0,0
1,67821090425,3,3.0,0,1,0,0
2,11078685487,4,23.0,0,1,0,0
3,50900226234,1,1.0,0,1,0,0
4,43187943268,2,9.0,1,0,0,0

### Salvando tabela

In [37]:
con = sql.connect("../dados/sql/base_completa.db")
df_diap.to_sql("diap",con,if_exists="replace", index=False, index_label="CPF")
con.close()

## Exemplo de abertura de base sql e carga em dataframe

In [38]:
con = sql.connect("../dados/sql/base_completa.db")

In [39]:
df=pd.read_sql("select * from cadastro",con)

In [40]:
df.head()

,CPF,NM_CANDIDATO,DT_NASCIMENTO,SG_UF_NASCIMENTO,NM_MUNICIPIO_NASCIMENTO,DS_GENERO,DS_GRAU_INSTRUCAO,DS_ESTADO_CIVIL,DS_COR_RACA,DS_OCUPACAO,VL_BENS,ANO_ELEICAO,DS_CARGO,SG_PARTIDO,SG_UE,SQ_CANDIDATO,NM_URNA_CANDIDATO,NR_IDADE_DATA_POSSE,NM_EMAIL
0,23019093104,WELLINGTON ANTONIO FAGUNDES,31/05/1957,MT,RONDONOPOLIS,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,DEPUTADO,8666604.04,2014,SENADOR,PR,MT,110000000293,WELLINGTON FAGUNDES,57.0,#NULO#
1,93565968834,JOSE SERRA,19/03/1942,SP,SAO PAULO,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,ECONOMISTA,1553822.22,2014,SENADOR,PSDB,SP,250000001674,JOSE SERRA,72.0,SECRETARIA.SERRA@GMAIL.COM
2,78229766134,JOSE ANTONIO MACHADO REGUFFE,05/09/1972,RJ,RIO DE JANEIRO,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,DEPUTADO,2793650.22,2014,SENADOR,PDT,DF,70000000436,REGUFFE,42.0,#NULO#
3,00274003953,ALVARO FERNANDES DIAS,07/12/1944,SP,QUATA,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,SENADOR,2912001.70,2014,SENADOR,PSDB,PR,160000000560,ALVARO DIAS,70.0,ESCRITORIO@ALVARODIAS.COM.BR
4,26472058768,RONALDO RAMOS CAIADO,25/09/1949,GO,ANAPOLIS,MASCULINO,SUPERIOR COMPLETO,CASADO(A),BRANCA,MÃDICO,7232461.92,2014,SENADOR,DEM,GO,90000000605,RONALDO CAIADO,65.0,MARCOSMOZAR@HOTMAIL.COM

In [41]:
df_1=pd.read_sql("select * from bens where cpf=274003953",con)

In [42]:
df_1

,CPF,ST_DECLARAR_BENS,CD_TIPO_BEM_CANDIDATO,DS_TIPO_BEM_CANDIDATO,DS_BEM_CANDIDATO,VR_BEM_CANDIDATO
0,274003953,S,31.0,AÃ§Ãµes (inclusive as provenientes de linha te...,"6.000 AÃÃES DA VALE, 2.752 PETR4, 5.492 BBAS...",255399.65
1,274003953,S,61.0,DepÃ³sito bancÃ¡rio em conta corrente no PaÃ­s,SALDO CONTA CORRENTE BANCO ITAU,10.00
2,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,JCP BANCO BRADESCO,658.20
3,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,BANCO DO BRASIL BB MULT ALLCATION,232829.08
4,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,BANCO DO BRASIL RF LP IND PRE PVT,243000.00
5,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,BANCO DO BRASIL BB MM ALOC CONS PRI,0.29
6,274003953,S,32.0,Quotas ou quinhÃµes de capital,QUOTAS CAPITAL SOCIAL CAD TRADE EMPREENDIMENTO...,1406210.00
7,274003953,S,21.0,"VeÃ­culo automotor terrestre: caminhÃ£o, autom...",VEÃCULO BMW 320 IA ANO 2003,128000.00
8,274003953,S,61.0,DepÃ³sito bancÃ¡rio em conta corrente no PaÃ­s,SALDO CONTA CORRENTE BANCO DO BRASIL,48394.85
9,274003953,S,59.0,Outros crÃ©ditos e poupanÃ§a vinculados,DEPÃSITO JUDICIAL TJDFT,160633.36
10,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,BANCO DO BRASIL BB REF DI PLUS EST,51735.72
11,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,BANCO DO BRASIL BB MM ALOC CONS PRI-,275095.63
12,274003953,S,45.0,"AplicaÃ§Ã£o de renda fixa (CDB, RDB e outros)",BANCO DO BRASIL CDB DI,500.00
13,274003953,S,49.0,Outras aplicaÃ§Ãµes e Investimentos,BANCO DO BRASIL B REF DI PRIVATE,109534.92

In [43]:
con.close()

# Para verificar o conteúdo da base por uma ferramenta externa utilize
# https://sqlitebrowser.org/